spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: challengeSermaluc
  cloud:
    config:
      name: challengeSermaluc
  jackson:
    serialization:
      write-dates-as-timestamps: false
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        validator:
          apply_to_ddl: false

info:
  project:
    name: Mantenimiento de Usuario
    description: Microservicio de mantenimiento de los usurios
    version: 1.0.0

application:
  client:
    api:
      path: "/channel/v1"

  parameter:
    message:
      correcto: 'Ejecución correcta.'
      errorGenerico: 'Ocurrió un error inesperado.'

security:
  jwt:
    token:
      secret-key: sermaluc-tokenx-serma
      expire-length: 300000

logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: DEBUG

server:
  port: 8092

management:
  endpoints:
    web:
      exposure:
        include=*:

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs
  version: v1


user:
    domain:
      pattern: "^(.+)@(domain.cl)$"
      error-format: "El correo debe seguir el siguiente formato: example@domain.cl"
      error-email-exist: "EL correo ya existe, use otro correo."
    password:
      pattern: "^(?=.*\\d){2}(?=.*[a-z])(?=.*[A-Z]).{4,}$"
      error-format: "Contraseña inválida, debe contener una Mayúscula, minúsculas y dos números"